data:
  root_dir: /root/autodl-tmp/CryFold/Datasets
  # Directory for storing cached preprocessed cubes
  cache_dir: /root/project/Calpha/data_cache2
  split_ratio:
    train: 0.8
    val: 0.2
  num_workers: 16
  crop_size: 64
  overlap: 0.0
  d0: 3.0
  voxel_size: 1.6638
  batch_size: 16
  max_samples: 1000
  min_ca_atoms: 5

training:
  lr: 3e-4
  weight_decay: 1e-4
  epochs: 100
  soft_weight: 0.5
  checkpoint_dir: /root/autodl-tmp/CryFold/checkpoints3
  device: cuda
  grad_clip: 1.0
  seed: 1
  final_div_factor: 100

augmentation:
  # Number of rotation samples for data augmentation; if set to 0 no rotation is applied.
  rotation_samples: 1
  noise_prob: 0.5
  noise_std: 0.05
  noise_multiplier: 1.0